### ISSUE TITLE
Circuit I/O API

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#133]
# RFC: Circuit I/O API

This RFC proposes an API for feeding data to a circuit (so really just the "I"
part of "I/O" for now) and for driving the execution of the circuit with and
without a multithreaded runtime.

## Model of Computation: Synchronous Transactions

A transaction is the user's view of one iteration of a synchronous circuit.  It
consumes a bunch of input data and produces corresponding outputs.  A new
transaction cannot be started until the current transaction completes (however,
the multithreaded API allows pushing data to the circuit while a transaction is
running; this data will be processed by the next transaction).  Transactions
cannot be rolled back.  A transaction also cannot fail.  An error while
executing a transaction (e.g., out of memory or disk read error) leaves the
circuit in a failed state, at which point it needs to be restarted (possibly
from the last checkpoint).

One might argue that this notion of a transaction is weak compared to what
people normally expect.  I don't mind using different terminology.

### Input handles

An input handle is a handle to an input stream of a circuit that can be used to
feed data to it.  Implementation-wise, input handles connect to special source
operators of type `Input`:

```
                               Circuit
                ┌──────────────────────────────────┐
┌──┐            │  ┌────────┐ Stream<T1>           │
│h1├────────────┼─►│Input1  ├────►                 │
└──┘            │  └────────┘                      │
                │                                  │
┌──┐            │  ┌────────┐ Stream<T2>           │
│h2├────────────┼─►│Input2  ├────►                 │
└──┘            │  └────────┘                      │
                │                                  │
┌──┐            │  ┌────────┐ Stream<T3>           │
│h3├────────────┼─►│Input3  ├────►                 │
└──┘            │  └────────┘                      │
                └──────────────────────────────────┘
```

An input handle works with both with and without a multithreaded runtime.
In the former case it can be used to push data to the circuit from multiple threads,
asynchronously with the execution of the circuit.

#### `InputHandle<T>`

A handle to an input stream holding values of type `T`. `T` is not necessarily a collection type (`Batch`).  It can be for instance a single number representing physical time.

Methods:

- `set_for_worker(&self, worker_index: usize, val: T)` - set value to send to the
  stream for the specified worker during the next transaction.

- `set_for_all_workers(&self, val: T)` - set value to send to the stream
  for the next transaction.  The same value will be sent to all worker threads
  (useful, e.g., for physical clock input, which must be consistent across workers).

Workers whose inputs have not been set using one of these methods will receive `T::default()`.

#### `IndexedZSetHandle<K, V, W>`

A handle to a collection of weighted (key, value) tuples.  Automatically shards tuples
across workers.

Methods:

- `push(&self, k, v, w)`
- `push_tuples(&self, tuples: &[(K, V, W)])`
- `rollback(&self)` - clear all uncommitted updates

#### `SetHandle<T>`

A handle to a collection that behaves as a set: all values have weight 1, duplicate
inserts and deletes are ignored. Automatically shards values across workers. DBSP
will internally cache the contents of the set (in a trace).

Methods:

- `delete(k)` - delete value if exists
- `insert(k)` - insert value if does not exist
- `rollback(&self)` - clear all uncommitted updates

#### `MapHandle<K, V>`

A handle to a collection that behaves as a key-value map: exactly one value per key, all weights
are 1. Automatically shards key/value pairs across workers.  DBSP internally stores the contents
of the map (in a trace).

Methods:

- `delete_key(k)` - delete the value associated with a key (if exists)
- `upsert(k, v)` - insert a key/value tuple, deleting existing values associated with the key, if any.
- `rollback(&self)` - clear all uncommitted updates

At commit time, updates are applied in the order they are submitted.

### `CircuitHandle`

A handle to a circuit running in the local thread.  This abstraction already
exists under an unfortunate name `Root`.

- `step(&self)` (needs a better name) - runs the circuit for a single clock cycle, feeding any
  inputs accumulated since the previous call.
- `compact(&self) -> bool` - Do some trace compaction work.  Since the circuit runs on the
  caller's instruction pointer, this needs to be scheduled explicitly.  Returns `true` if
  non-zero amount of compaction was performed. `false` means there's nothing more to compact.

### `DBSPHandle`

A handle to a multithreaded runtime running `N` identical copies of a circuit.
This abstraction already exists under the name `Runtime`.

- `run(Fn(Circuit<()>) -> Result<T, DBSPError>) -> (DBSPHandle, T)`

- `commit() -> Result<(), DBSPError>` - runs all copies of the circuit in the runtime for one
  clock cycle, consuming any inputs received since the previous `commit`.  The methods returns
  after fully processing all inputs and producing results.  Multiple concurrent calls are
  serialized.

- `stop` - terminate the runtime along with all workers.

- TODO: Monitoring/profiling APIs.

**Comment by mbudiu-vmw** [comment]
I would separate concerns into two separate pieces: an API to push *changes* to DBSP, and a transaction manager, which can assemble the changes. the TM is a separate optional software component. I don't know exactly how multi-threading would play with this.

A change is essentially a tuple of ZSets: one for each input.
That's what the output of a DBSP circuit can be too: a tuple that has a ZSet for each output. 
Calling a DBSP circuit with a change produces synchronously another change.
This API is very simple, it is statically typed, and it is very efficient.

The TM is much more complicated, and may encompass almost everything you are talking about. It will need to be dynamically-typed. We may need something like the DDValue.

**Comment by mbudiu-vmw** [comment]
Of course the TM has to maintain state.
But why force the circuit to maintain state if it is not necessary?

**Comment by mbudiu-vmw** [comment]
And the TM has to keep a shadow of the state anyway, to be able to rollback a transaction on failure. You can't rely on the circuit for that.

**Comment by ryzhyk** [comment]
We don't. The circuit will only maintain state for `SetHandle` and `MapHandle`, i.e., when the user explicitly wants to eliminate duplicates.

**Comment by mbudiu-vmw** [comment]
That's why DDlog transaction rollback didn't work - there was no way to undo a set of partial changes.

**Comment by mbudiu-vmw** [comment]
But the TM will in general need to maintain state to reject incorrect transactions, e.g., which delete non-existent elements.

**Comment by ryzhyk** [comment]
We will actually be able to implement rollback, which will simply drop uncommitted changes.

**Comment by ryzhyk** [comment]
Actually, rollback is more subtle.  But in any case it doesn't require an extra copy of state in the TM.

**Comment by mbudiu-vmw** [comment]
I think it does. You tentatively apply changes, and then if they fail you need to revert to the previous state. You don't want the circuits to do that. Circuits should only process legal changes, when they are complete.

**Comment by mbudiu-vmw** [comment]
A "real" TM may itself be much more complicated than all of DBSP together. It can potentially do concurrency control using locks and all that stuff. It can have multiple implementations too - e.g., as you propose, using a single transaction at a time.

**Comment by ryzhyk** [comment]
> But the TM will in general need to maintain state to reject incorrect transactions, e.g., which delete non-existent elements.

Such deletes will simply be ignored.

**Comment by mbudiu-vmw** [comment]
> > But the TM will in general need to maintain state to reject incorrect transactions, e.g., which delete non-existent elements.
> 
> Such deletes will simply be ignored.

what mechanisms causes them to be ignored? zsets with negative weights will be accepted by any DBSP circuit.

**Comment by ryzhyk** [comment]
>A "real" TM may itself be much more complicated than all of DBSP together. It can potentially do concurrency control using locks and all that stuff. It can have multiple implementations too - e.g., as you propose, using a single transaction at a time.

Exactly, which is why this does not belong in DBSP.  People are free to build all kinds of wrappers of course.

**Comment by mbudiu-vmw** [comment]
But you *are* building a wrapper.

**Comment by ryzhyk** [comment]
> what mechanisms causes them to be ignored? zsets with negative weights will be accepted by any DBSP circuit.

The new `Input` operator(s) I will implement.  Alternatively, we could just use `distinct`.

**Comment by mbudiu-vmw** [comment]
A circuit that computes on sets has to maintain the invariant that all inputs (integrals of changes) are sets.
You can only apply distinct to the integral, not to the change.
I think the TM should maintain the integral.

**Comment by ryzhyk** [comment]
> But you are building a wrapper.

Not a wrapper. A very light-weight API that sends data directly to the circuit.

**Comment by ryzhyk** [comment]
> A circuit that computes on sets has to maintain the invariant that all inputs (integrals of changes) are sets.
> You can only apply distinct to the integral, not to the change.

Of course.  This is exactly what the `distinct` operator does.  It integrates changes into a trace and enforces set semantics incrementally and concurrently.

**Comment by mbudiu-vmw** [comment]
What you are talking about is (\lift distinct)^\Delta. distinct is just a simple pointwise operator on zsets.

**Comment by ryzhyk** [comment]
yes

**Comment by mbudiu-vmw** [comment]
That's a different semantics than DDlog, in DDlog such changes were not ignored. It is a legitimate design, but users may want both behaviors. I think they can be implemented by having different TMs with different APIs and policies.

**Comment by mbudiu-vmw** [comment]
For example, if you run DBSP next to a real database, the TM is the one in the real DB, and you accept all transactions it sends your way. You don't need any validation.

**Comment by ryzhyk** [comment]
Agreed. This API allows building any such TM without introducing unnecessary overhead and without enforcing any particular design.

**Comment by mbudiu-vmw** [comment]
How about we start from a simple use case, where users instantiate a circuit and send data to it over the network?
How is that supported?

**Comment by ryzhyk** [comment]
I don't think anything involving a network is simple :)  This is a local API.

**Comment by ryzhyk** [comment]
> We will actually be able to implement rollback, which will simply drop uncommitted changes.

Thinking more about this, circuit-wide rollback is probably too high-level an operation for this API. Instead I will add the `rollback` method to drop any uncommitted changes (i.e., changes since the last `commit` call) from a specific input handle.  This enables more fine-grained control, e.g., in the networking example, assuming we have changes arriving from multiple senders and one of them dies, we can clear uncommitted updates from the associated handle only.

**Comment by mbudiu-vmw** [comment]
Yes, that's the right way. The TM buffers all pending changes, validates them, and rolls them back if they are not fit.
It has to have internal state for that - that's what the rollback will do.
One the changes are validated, they are accumulated and sent to the circuit as a single big change.
