### ISSUE TITLE
rewind_keys sets valid unconditionally in OrdZSet

### ISSUE THREAD

**Issue by gz** [vmware/database-stream-processor#145]
this test currently passes, but in discussion with leonid I think both cursors should have !val_valid() (e.g., spine impl is correct but OrdZSet isn't).
OrdZSet sets valid to true unconditionally on every `rewind_keys` but should probably check if the set is empty (or check something stronger/weaker, not sure what the right condition is).

```
#[test]
fn silly() {
    let zset_builder = ord::zset_batch::OrdZSetBuilder::<usize, usize>::new(());
    let zset = zset_builder.done();
    let mut cursor = zset.cursor();
    cursor.rewind_keys();
    assert!(cursor.val_valid());

    let mut spine = Spine::<OrdZSet<usize, usize>>::new(None);
    spine.insert(zset.clone());
    let mut spine_cursor = spine.cursor();
    spine_cursor.rewind_keys();
    assert!(!spine_cursor.val_valid());
}
```

**Comment by ryzhyk** [comment]
It appears the semantics of `val_valid` is the value is valid assuming that `key_valid` holds. It's a performance thing that reduces the number of checks in the code based on the premise that the client always makes sure the cursor points to a valid key before looking at values.

**Comment by mbudiu-vmw** [comment]
Can we close this issue?
