### ISSUE TITLE
aggregate does not produce results when applied to empty sets

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/database-stream-processor#150]
This is actually wrong, the aggregate function should be invoked even when the argument set is empty.
For example, in SQL COUNT(*) would return 0 for an empty table, and not an empty collection.

**Comment by mbudiu-vmw** [comment]
However, this seems to be a problem with DBSP, because then this function does not preserve zeros, so perhaps it is not time-invariant.

**Comment by mbudiu-vmw** [comment]
Yes, it looks like the function "makeset" is in fact not time-invariant, since it does not preserve zeros.
I suspect that this is actually not a problem for groupby-aggregate, but it is for simple aggregates, as in the example above.
Given this fact I actually don't know how to implement SELECT COUNT(*) in DBSP. It may not be possible.

**Comment by ryzhyk** [comment]
Once we have an aggregate over entire ZSet' as opposed to group-by-aggregare, it will naturally work this way--return zero for an empty z-set.

**Comment by mbudiu-vmw** [comment]
This should be equivalent with group on (). Moreover, the actual sql semantics is more complicated, but can be always expressed with a fold.

**Comment by ryzhyk** [comment]
I'm not sure it should. Index by () applied to an empty z-set should return an empty indexed z-set, otherwise it wouldn't be zero preserving.

**Comment by mbudiu-vmw** [comment]
Exactly, how can then an aggregate return a non empty set?

**Comment by ryzhyk** [comment]
Aggregate over an empty z-set should return zero, which is perfectly zero preserving. It's just apparently not the same as index by () followed by an aggregate.

**Comment by ryzhyk** [comment]
I.e., it should return a scalar value 0.

**Comment by mbudiu-vmw** [comment]
Sum in sql over an empty set is null

**Comment by ryzhyk** [comment]
SQL intricacies aside, indexing by `()` of an empty z-set returns an empty indexed z-set because we don't store keys with zero weights,  (i.e., not in the support).  So an empty indexed Z-set is equivalent to an indexed Z-set with a single key `()` and value `0`. So the semantics is correct, and it's just a matter of representation whether you output it as an empty set of rows or one row with value `0`.

**Comment by mbudiu-vmw** [comment]
Can you write a test for this case?

**Comment by ryzhyk** [comment]
Sure, but the test will output an empty z-set when counting (or summing up) an empty input z-set.  Is that what you expect?

**Comment by mbudiu-vmw** [comment]
I don't know how to implement sum(x) in dbsp that returns null for an empty input

**Comment by ryzhyk** [comment]
I suppose the co-domain of this operator is `Option<int>`, with `None` playing the role of 0, so a key that is not in support of a Z-set implicitly has sum `None` (or null).

**Comment by ryzhyk** [comment]
And unlike normal `sum`, I don't think this operator is linear.

**Comment by mbudiu-vmw** [comment]
I am afraid it's not time invariant either

**Comment by ryzhyk** [comment]
Can you explain why?  That'd make it pretty evil.

**Comment by mbudiu-vmw** [comment]
The def requires op \circ z = z \circ op, which requires op(0) = 0. But makeset does not produce the empty set for a zero input

**Comment by ryzhyk** [comment]
I think op(0) = 0 holds. If input z-set has empty support, then so does the output.

**Comment by mbudiu-vmw** [comment]
Not for makeset, which the last step of your aggregate

**Comment by ryzhyk** [comment]
makeset should only assign weight 1 to keys in the support of its input.  If the key is not in the support (i.e., its weight is None), makeset will not touch it.

**Comment by mbudiu-vmw** [comment]
Let's talk tomorrow. I really don't know how to implement the SQL aggregates

**Comment by mbudiu-vmw** [comment]
Probably DBSP is correct,, as it maps empty sets to empty sets always; the problem is in SQL really, but there is a way to do it. Closing.
