### ISSUE TITLE
In a pipeline with multiple inputs, all inputs are labeled `input0`

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#273]
![image](https://user-images.githubusercontent.com/8323135/212986477-2d310da3-5055-4173-b877-2c59cf46d299.png)

**Comment by ryzhyk** [comment]
A bigger issue: when I click on the second input, it briefly shows its status before jumping back to input0.

**Comment by mbudiu-vmw** [comment]
Is there a quick way to get such a pipeline for testing?

**Comment by ryzhyk** [comment]
Fixed in #276.
