### ISSUE TITLE
Poll for status changes

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#275]
Can we have the `Status` page poll for changes to status, so we don't need to keep checking?

**Comment by mbudiu-vmw** [comment]
How long?
Until you navigate out?

**Comment by ryzhyk** [comment]
> How long? Until you navigate out?

Yep

**Comment by mbudiu-vmw** [comment]
I will refresh as long as the result is "Compiling"

**Comment by ryzhyk** [comment]
Fixed in #276.
