### ISSUE TITLE
End-to-end test using docker

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#312]
- Build a docker container on every commit in CI (just don't upload it to the repository).
- Run an end-to-end API test against it, e.g., using the python API test script.

This will help debug issues with the container and improve our end-to-end test coverage.

One thing missing currently is shared file system access, so the client cannot easily create files visible inside the container.

@lalithsuresh

**Comment by lalithsuresh** [comment]
@ryzhyk we can close this?
