### ISSUE TITLE
[JIT] Neg operator not recognized

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/database-stream-processor#367]
The Rust code seems to have a "Neg" operator, but attempts to use in the JSON cause validation errors:
`json validation error at `/nodes/2728`: {"Neg":{"inputs":[2727]}} is not valid under any of the given schemas`
I used Neg exactly as Distinct would be used.

**Comment by Kixiron** [comment]
The error is correct, `Neg` looks like this
```rust
pub struct Neg {
    input: NodeId,
    output_layout: LayoutId,
}
```
There's no `inputs` field in it
