### ISSUE TITLE
[RFC] Use hashbrown directly instead of HashMap.

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#38]
### Is your feature request related to a problem? Please describe.

HashMap doesn't allow creating an entry from a reference to a key (this feature is currently unstable and looks like it won't be stabilized any time soon). HashMap is just a wrapper around hashbrown, which does support this.  I suggest we use hashbrown directly to get better performance.

@mbudiu-vmw , @Kixiron , what do you think?

### Describe the solution you'd like

-

**Comment by mbudiu-vmw** [comment]
You don't have to keep all the titles in the issue if the sections are empty.
I looked at this a bit when I wrote the ZSet, but I am in general weary of using non-standard code. The feature request has been open since 2015. Why hasn't this API been merged?

**Comment by ryzhyk** [comment]
`hashbrown` has 39M downloads from crates.io.  This is as standard as it gets. The feature hasn't been stabilized because the API is considered too complicated.  `hashbrown` will soon provide a simpler API to access entries by reference. But it will probably take a couple more years for std to stabilize it :)

**Comment by ryzhyk** [comment]
In fact the API is already there. Here it is: https://docs.rs/hashbrown/0.12.0/hashbrown/hash_map/struct.HashMap.html#method.entry_ref

**Comment by Kixiron** [comment]
Using hashbrown is perfectly fine, I've done it plenty before for various reasons

**Comment by ryzhyk** [comment]
Implemented in #39
